language: python
python:
  - "3.6"
env:
  global:
    - secure: "tsfhGyBBQTAMHXgOPC1TWNXWtEYmSp1ckgtape9wd0R4Tywjy72V9XnGVA9JAG+MgCIivlbfsxnbsVtIiMqBFrzwRrZyV9czzpG8du2srhLFxR+Pki5oj7feTs6CPr+Huya4EtRgArk+nkvKUVdPGC77m1zpkXrvKx1e1vhQA5mkikTOqwYsOd3NYewVQ0aEb3NwSlwiE/f/NdtnWzHLZWZuZbq0rU75VGTGmU66YSvhOixg2FSNQsifqu3/L+qC6o/sB3T5c8fjyo9Hj6vCjd0siKqdXFwMzUfcBTYaMRojTlGGBYwEy8M/Hk1E67LR674k6IDHWRos8NAN94zr5CcaEl7a0AJcnHTZz+c9fTdGXshcbzXJV30IBgHUITmCQs8elSWeEXUfBhhOKdFWDGR1qu/w99MHtXlWaJeJgqhEQzSuSBDIuaOFUlr7GX90TWIIo17a2+GL7sdvNEmJ4IMkOYz3lzrK4/zw2FSBrqTW43Hu1JxhZu95jgQ17iAhYYp0oWOY6k8Kp4JQcDxnFAK8/14ViRQt2fNPRIvBVFaY8A2s2Jr4AwGvsWpoKgugfk3ePxWlDHIIv4ASIfYce7OJxoTvtn2Uz9IR23M/pvYYVwnZGX/TMfwYqhSpgD4cKu7Kuup+3LwjXbX77Id/ElY2G6e8cKtDBRrAWXwkacA="
    - secure: "vSlFkbjjzfzZ+iUeTKWpTrGAvU9qBM7o97b2mGWwdxce/kCJjTxGawcyPkcbCpipJMqz+JE0u/x2IXridzEykCSL7tt2qqmNpWqrmvTMfwOcTeQoggdylNUxtTA85AlzA3D3YxCfO3F1wPGMrK/8Rc0XYmaw3aVFiavw2BZiTQhFlfA16cmR9QGMTUPW9RMhDmcGSk+1n4Cbwsxxi5Jyas2RBhioomNsYH7NUfKAmFd6XOSLkJQfVZmUBhZLWkrpU32PjMGmDXYt/9K14sxpXe0hk4oTzZYvEAfz+P+QoQONz+OfkLP37T/KT65G7Q70P8d9KWzGUQy0WiBLSYddmfrRgtvgTwhpS3Y7z0orsTaPM0nLtfo9v59adRTDNqJBJADUbGNQ3OeGdW6rUr4MV04MqhUiEvZQ3tPJq16VdLyUfLRRouEFBSK039dmdID0nPdiyB+ud4BGuG97lZLAfyjEx9HrUNKk8SJ7S5Vo3RsN5PgodXd3N+YPQfqTFQ3XSmPOaV+q2oA/PQL8j+v6NY9HTEiyq7Om1xYFBQC9Sqi/87dmJ00CkQVEkNlLFR1AxzeVUFajdFTrjcsqlRik3k7/vpoLJR4Fp4Ry42Bp6pnHI9d6JHHuZaGDnNCYRXg68TuF37xHJhA9ZYy+WKBGeXiWOihWFocIg3IpJVhcrac="
# command to install dependencies
before_install:
  - export BOTO_CONFIG=/dev/null
  - pip install flake8
install:
  - pip install -r requirements.txt
  # This is a workaround for issue: https://github.com/spulec/moto/issues/1941
  - pip install -e git+https://github.com/spulec/moto@master#egg=moto
# command to run tests
script:
  - make flake8
  - PYTHONPATH=. python -m pytest tests/